### ISSUE TITLE
Could you add the following new items to this enum?

### ISSUE THREAD

**Issue by jesusrv26** [tenkyu/KieServerAdapter#1]
Hi!
Thank you for shared the library.
I hava new develompment case where I need to set and get variable global.
I added new commands in my local project but I can´t override KieCommandTypeEnum  to add new elements.

Could you add the following new items to this enum?

`public enum KieCommandTypeEnum : byte
        {
            SetGlobal = 20,
            Insert = 10,
            FireAllRules = 2,
            GetGlobal = 1,
            StartProcess = 0
        }
`

Thank you for your attention

**Comment by tenkyu** [comment]
KieCommandTypeEnum is defined in ICommand.cs 
Please add new commands here.

SetGlobal and GetGlobal commands is not covered now, may be you want to add this features :)

**Comment by jesusrv26** [comment]
Hi!
I have added new pull request with SetGlobal and GetGlobal commands support

**Comment by tenkyu** [comment]
Jesus added SetGlobal and GetGlobal features

**Comment by jesusrv26** [comment]
Hi @tenkyu.
Could you publish the new version in the NuGet to update from visual studio?
Thank you!

**Comment by tenkyu** [comment]
Hi @jesusrv26 
I uploaded the package, https://www.nuget.org/packages/KieServerAdapter/1.0.4 (see the Authors title :))
I added you  as a contributer to repository.

**Comment by jesusrv26** [comment]
Thanks! :)

**Comment by jesusrv26** [comment]
Hi @tenkyu
I updated now the project from NuGet in Visual Studio, but the downloaded version, 1.0.4, not contains the latest changes. Could you revised this?

**Comment by tenkyu** [comment]
Please re-check https://www.nuget.org/packages/KieServerAdapter/1.0.5

**Comment by jesusrv26** [comment]
Yes. Now it´s Ok.
Thanks! :)
